all:
	ec -config prodcons.ecf -target prodcons -c_compile -finalize
single:
	ec -config prodcons_single.ecf -target prodcons -c_compile -finalize
prof:
	eve -config prodcons.ecf -target prodcons -c_compile -finalize
